# ndarray 연산
- NumPy 배열 간 연산 정리임
- 원소별 연산, broadcasting, 행렬곱, axis 연산 포함함


In [1]:
import numpy as np

## n차원 배열 연산
- 같은 shape끼리 원소별 연산 가능함
- 같은 위치의 값끼리 계산함
- 결과 shape도 기존 shape와 같음


In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.full_like(arr1, 2)

print("arr1: ", arr1)
print("arr2: ", arr2)

print("arr1 + arr2: \n", arr1 + arr2)
print("arr1 - arr2: \n", arr1 - arr2)
print("arr1 * arr2: \n", arr1 * arr2)
print("arr1 / arr2: \n", arr1 / arr2)
print("arr1 // arr2: \n", arr1 // arr2)
print("arr1 % arr2: \n", arr1 % arr2)
print("arr1 ** arr2: \n", arr1 ** arr2)

arr1:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2:  [[2 2 2]
 [2 2 2]
 [2 2 2]]
arr1 + arr2: 
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr1 - arr2: 
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
arr1 * arr2: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
arr1 / arr2: 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
arr1 // arr2: 
 [[0 1 1]
 [2 2 3]
 [3 4 4]]
arr1 % arr2: 
 [[1 0 1]
 [0 1 0]
 [1 0 1]]
arr1 ** arr2: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## broadcasting 연산 방식
- shape가 다른 배열도 규칙이 맞으면 연산 가능함
- 작은 배열을 큰 배열 shape에 맞춰 해석함
- 실제 배열을 복사해서 키우는 것은 아님

**broadcasting 규칙**
- 뒤쪽 차원부터 비교함
- 두 차원이 같으면 가능함
- 둘 중 하나가 1이면 가능함
- 둘 다 다르고 1도 아니면 불가함

![](https://d.pr/i/D0XITM+)
![](https://d.pr/i/fka9ED+)


In [4]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.full((3, ), 2) # [2,2,2]

print("arr1: \n", arr1)
print("arr2: ", arr2)

print("arr1 + arr2: ", arr1 + arr2)

arr1: 
 [[1 2 3]
 [4 5 6]]
arr2:  [2 2 2]
arr1 + arr2:  [[3 4 5]
 [6 7 8]]


In [6]:
arr = np.array([1,2])
print(arr.shape) # (2,)

print(arr1 + arr)
# (2,3) + (1,2)
# - 제일 끝 차원인 3, 2가 같지 않고, 둘 중 1이 없음
# -> 브로드캐스팅 불가

(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [11]:
# 스칼라(값 1개) 또는 길이(size)가 1인 배열과의 연산
# -> 전체 원소에 스칼라 또는 배열의 값을 적용

print("arr1:\n", arr1)
print("arr1 + 10:\n", arr1 + 10)
print("arr1 + [10]:\n", arr1 + [10])
print("arr1 + [[10]]:\n", arr1 + [[10]])
print("arr1 + [[[10]]]:\n", arr1 + [[[10]]])

arr1:
 [[1 2 3]
 [4 5 6]]
arr1 + 10:
 [[11 12 13]
 [14 15 16]]
arr1 + [10]:
 [[11 12 13]
 [14 15 16]]
arr1 + [[10]]:
 [[11 12 13]
 [14 15 16]]
arr1 + [[[10]]]:
 [[[11 12 13]
  [14 15 16]]]


In [16]:
arr3 = np.array([[1], [2]])
print("arr3:\n", arr3) # arr3.shape = (2, 1)
print("arr1:\n", arr1) # arr1.shape = (2, 3)

print("arr1 + arr3:\n", arr1 + arr3)
# arr3.shape = (2,1) -> (2,3)으로 브로드캐스팅
# [[1,1,1]
#  [2,2,2]]

arr3:
 [[1]
 [2]]
arr1:
 [[1 2 3]
 [4 5 6]]
arr1 + arr3:
 [[2 3 4]
 [6 7 8]]


In [18]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
arr2 = np.array([5, 6, 7])
arr3 = arr1 + arr2 # 5 6 7 / 6 7 8 / 7 8 9
print("arr3:\n", arr3)
print("arr3.shape: ", arr3.shape)

arr3:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
arr3.shape:  (3, 3)


In [17]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
arr3 = arr1 + arr2 # 6 7 / 9 10
print("arr3:\n", arr3)
print("arr3.shape: ", arr3.shape)

arr3:
 [[ 6  7]
 [ 9 10]]
arr3.shape:  (2, 2)


## 행렬곱셈 Matrix Multiplication
- 점곱연산 Dot Product, 내적이라고도 함
- NumPy의 `*` 연산과 행렬곱은 다름
- `*`: 같은 위치 원소끼리 곱함
- `@`, `np.dot()`, `np.matmul()`: 행렬곱 수행함

**계산 방식**
- 왼쪽 행과 오른쪽 열을 짝지어 계산함
- 같은 위치끼리 곱한 뒤 모두 더함
- 결과의 한 칸은 왼쪽 행과 오른쪽 열의 내적값임

**shape 조건**
- 첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 같아야 함
- 행렬곱 shape: `(m, n) @ (n, p) -> (m, p)`
- 결과 shape: 바깥쪽 숫자인 `(m, p)`


- **수식**: 행렬 $ A $가 $ m \times n $ 크기이고, 행렬 $ B $가 $ n \times p $ 크기일 때, 행렬 곱 $ A \times B $의 결과는 $ m \times p $ 크기의 행렬이다. 곱셈 과정은 다음과 같다:
  $$
  (A \times B)_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}
  $$
  즉, $ A $의 i번째 행과 $ B $의 j번째 열에 해당하는 원소들을 곱하고, 그 결과를 더하여 새로운 행렬의 $ (i, j) $ 위치에 배치한다.

- **예시**:
  $$
  A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}
  $$
  $$
  A \times B = \begin{pmatrix} 1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\ 3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8 \end{pmatrix} = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
  $$

- **결과**: 새로운 **행렬**.

In [24]:
a = [[1,2],
     [3,4]]
b = [[5,6],
     [7,8]]

a = np.array(a)
b = np.array(b)

# NumPy * 연산
print("a * b:\n", a * b)

print("-" * 20)
# 내적 연산(행렬 곱)
print(np.matmul(a, b)) # == np.dot(a, b)

print(a @ b) # == np.dot(a, b)

a * b:
 [[ 5 12]
 [21 32]]
--------------------
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [25]:
c = np.array([[1, 2]]) # 1 2 -> (1, 2)
d = np.array([[3], [4]]) # 3 / 4 -> (2, 1)

print("c @ d = ", c @ d)

c @ d =  [[11]]


In [26]:
e = np.array([[1, 2, 3],
              [4, 5, 6]]) # (2,3)
f = np.array([[7, 8],
              [9, 10],
              [11, 12]]) # (3,2)

print("e @ f = ", e @ f) # (2,2)

e @ f =  [[ 58  64]
 [139 154]]


## 기타 연산
- 절대값, 반올림, 올림, 내림, 버림 등 기본 수학 함수 정리임


In [27]:
# 절대값
arr1 = np.array([[1, -2], [3, -4]])
print(np.abs(arr1))

[[1 2]
 [3 4]]


In [28]:
# 올림(ceil), 내림(floor), 반올림(round), 버림(trunc)
arr2 = np.array([-1.234, 1.234, 2.345, 3.456, 4.567])
print("np.ceil(arr2): ", np.ceil(arr2))
print("np.round(arr2): ", np.round(arr2))

print("np.floor(arr2): ", np.floor(arr2))
print("np.trunc(arr2): ", np.trunc(arr2))

np.ceil(arr2):  [-1.  2.  3.  4.  5.]
np.round(arr2):  [-1.  1.  2.  3.  5.]
np.floor(arr2):  [-2.  1.  2.  3.  4.]
np.trunc(arr2):  [-1.  1.  2.  3.  4.]


### axis 속성
- 연산을 처리할 축 지정값임
- `axis=None`: 전체 값을 하나로 펼쳐 계산함
- `axis=0`: 행 방향으로 내려가며 계산함, 열별 결과가 남음
- `axis=1`: 열 방향으로 이동하며 계산함, 행별 결과가 남음
- 핵심: axis는 계산 후 사라지는 축임

In [31]:
arr = np.arange(1,7).reshape(2,3)
# [[1 2 3]
# [4 5 6]]

# 최솟값 구하기
print("arr.min(axis=None): ", arr.min(axis=None)) # 전체 최솟값

# axis=0: 행 방향으로 내려가면서 같은 열의 최솟값 구하기
print("arr.min(axis=0): ", arr.min(axis=0)) # [1 2 3]

# axis=1: 열 방향으로 오른쪽으로 이동하면서 같은 행의 최솟값 구하기
print("arr.min(axis=1): ", arr.min(axis=1)) # [1 4]

arr.min(axis=None):  1
arr.min(axis=0):  [1 2 3]
arr.min(axis=1):  [1 4]


In [32]:
# 합계
print("arr.sum() : ", arr.sum()) # axis 미작성 == 기본값 (axis=None)
print("arr.sum(axis=0) : ", arr.sum(axis=0))
print("arr.sum(axis=1) : ", arr.sum(axis=1))

arr.sum() :  21
arr.sum(axis=0) :  [5 7 9]
arr.sum(axis=1) :  [ 6 15]


In [33]:
# 평균 ndarray.mean() (mean == 수학적으로 평균이라는 뜻)
print("arr.mean() : ", arr.mean())
print("arr.mean(axis=0) : ", arr.mean(axis=0))
print("arr.mean(axis=1) : ", arr.mean(axis=1))

arr.mean() :  3.5
arr.mean(axis=0) :  [2.5 3.5 4.5]
arr.mean(axis=1) :  [2. 5.]
